language: python
dist: xenial
python:
  - "3.5"
services:
  - mysql
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-dev libmysqlclient-dev
  - sudo apt-get install libssl-dev libcurl4-openssl-dev
# command to install dependencies
install: pip install -r requirements/local.txt
# command to setup database
before_script:
  - mysql -e "CREATE DATABASE chris_dev CHARACTER SET utf8;" -uroot
  - mysql -e "GRANT ALL ON chris_dev.* TO 'chris'@'localhost' IDENTIFIED BY 'Chris1234';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'chris'@'localhost';" -uroot
  - python chris_backend/manage.py migrate
# command to run tests
script: python chris_backend/manage.py test
notifications:  slack: fnndsc:WtDpBdT7VxV8YVD4K0NPHnW1
