sudo: required
language: Python
dist: xenial
services:
  - docker
before_install:
  - docker-compose -v
  - docker -v
  - travis_wait 30 docker build -t fnndsc/chris_dev_backend . #TODO: ravig, Remove this.Tagging local image as fnndsc to avoid confusion in docker compose
before_script:
  - docker-compose up -d
  - docker-compose exec chris_dev_db sh -c 'while ! mysqladmin -uroot -prootp status 2> /dev/null; do sleep 5; done;'
  - docker-compose exec chris_dev_db mysql -uroot -prootp -e 'GRANT ALL PRIVILEGES ON *.* TO "chris"@"%"'
  - docker-compose exec chris_dev python manage.py migrate
# command to run both Unit and Integration tests
script:
  - docker-compose exec chris_dev python manage.py test --exclude-tag integration; echo "done"
notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
